In [2]:
#importing required liberary
import numpy as np
import pandas as pd

In [3]:
#import datasets
data=pd.read_csv("dataset.csv");

In [4]:
#reading 5 dataset
data.head()

x1        x2        x3          y
0  2.173282  2.350076  2.415250  35.708201
1  5.555118  5.993455  3.045520  60.201730
2  4.799505  3.901152  4.451028  56.969898
3  2.581442  5.075955  4.103971  54.576365
4  1.241630  4.261207  4.567827  50.139696

In [5]:
x1 = np.array(data['x1'])

In [8]:
x1[0:5]

array([2.17328187, 5.55511808, 4.79950491, 2.58144234, 1.24162955])

In [9]:
#Taking 70% of data as training set
k=(int)(0.7*data['x1'].size)
x=np.ones((k,4))
x[:,1:]=np.array(data.loc[:k-1,['x1','x2','x3']])
y=np.array(data.loc[:k-1,'y'])

In [17]:
x0 = x[:,0]

In [18]:
x1.shape

(700,)

In [19]:
x1 = x[:,1]
x2 = x[:,2]
x3 = x[:,3]

In [20]:
x2[0:5]

array([2.35007567, 5.99345518, 3.90115183, 5.07595546, 4.26120663])

In [21]:
X = [x0,x1,x2,x3]

In [52]:
grad = np.array([0.,0.,0.,0.])

In [53]:
theta = np.array([1.,1.,1.,1.])#theta_0,theta_1,theta_2,theta_3

In [54]:
learning_rate = 0.01

In [55]:
for _ in range(0,15000):
    for l in range(0,4):
        grad[l] = 0.0
    for i in range (0,100):
        pred = 0.0
        for j in range (0,4):
            pred += (theta[j] * X[j][i])
        #gra = dot - y[i]
        for k in range (0,4):
            grad[k] = grad[k]+(pred - y[i])*X[k][i]
            #grad[k] = grad[k] + (grad[k] * X[k][i])
    for z in range(0,4):
        theta[z] = theta[z] - (learning_rate*grad[z])/100

In [56]:
theta

array([10.60943035,  2.48880513,  3.57750762,  4.70566125])